FROM python:3.10-slim-buster

# Set root user for the initial setup
USER root

# Create application directory
RUN mkdir /app
WORKDIR /app

# Copy application files
COPY . /app/

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Set environment variables
ENV AWS_DEFAULT_REGION="us-east-1" \
    BUCKET_NAME="mynetworksecurity" \
    PREDICTION_BUCKET_NAME="my-network-datasource" \
    AIRFLOW_HOME="/app/airflow" \
    AIRFLOW_CORE_DAGBAG_IMPORT_TIMEOUT=1000 \
    AIRFLOW_CORE_ENABLE_XCOM_PICKLING=True

# Update and install dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends bash && \
    rm -rf /var/lib/apt/lists/*

# Initialize Airflow database and create admin user
RUN airflow db init && \
    airflow users create -e dsdd0511@gmail.com -f danish -l sharma -p admin -r Admin -u admin

# Ensure start.sh is executable
RUN chmod +x /app/start.sh

# Set entrypoint to use start.sh
ENTRYPOINT ["/bin/sh", "-c", "/app/start.sh"]